services:
  setono_sylius_elasticsearch_plugin.repository.elastic_search:
    class: Setono\SyliusElasticsearchPlugin\Repository\ElasticSearchRepository
    arguments:
      - "%setono_sylius_elasticsearch.max_filter_options%"

  setono_sylius_elasticsearch_plugin.transformer.product_transformer:
    class: Setono\SyliusElasticsearchPlugin\Transformer\ProductTransformer
    parent: fos_elastica.model_to_elastica_transformer

  Setono\SyliusElasticsearchPlugin\Controller\SearchController:
    public: true
    arguments:
      - "@sylius.repository.taxon"
      - "@sylius.repository.product_option"
      - "@sylius.repository.product_attribute"
      - "@fos_elastica.finder.products.default"
      - "@fos_elastica.finder.taxons.default"
      - "@sylius.context.locale"
      - "@sylius.context.channel"
      - "@setono_sylius_elasticsearch_plugin.repository.elastic_search"
      - "@event_dispatcher"
      - "%setono_sylius_elasticsearch.pagination%"

  setono_sylius_elasticsearch_plugin.property_builder.product_properties:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ProductPropertiesBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.product_position_builder:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ProductPositionBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.product_translations:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ProductTranslationsBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.option:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\OptionBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.attribute:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\AttributeBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.product_taxons:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ProductTaxonsBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.channels:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ChannelsBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.channel_pricing:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\ChannelPricingBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\Mapper\ProductTaxonsMapper
    arguments:
      - "@sylius.repository.channel"

  setono_sylius_elasticsearch_plugin.property_builder.loevgaard_brand:
    class: Setono\SyliusElasticsearchPlugin\PropertyBuilder\LoevgaardBrandBuilder
    arguments:
      - "@sylius.repository.channel"
    tags:
      - { name: kernel.event_subscriber }

  setono_sylius_elasticsearch_plugin.command.generate_config:
    class: Setono\SyliusElasticsearchPlugin\Command\SyncElasticCommand
    tags: [console.command]

  setono_sylius_elasticsearch_plugin.listener.product_variant_listener:
    class: Setono\SyliusElasticsearchPlugin\EventListener\ProductVariantListener
    arguments:
      - "@fos_elastica.object_persister.products.default"
      - "%setono_sylius_elasticsearch.enable_product_variant_listener%"
    tags:
      - name: 'doctrine.orm.entity_listener'
        event: 'postUpdate'
        entity: '%sylius.model.product_variant.class%'

  setono_sylius_elasticsearch_plugin.listener.product_taxon_listener:
    class: Setono\SyliusElasticsearchPlugin\EventListener\ProductTaxonListener
    arguments:
      - "@fos_elastica.object_persister.products.default"
      - "%setono_sylius_elasticsearch.enable_product_taxon_listener%"
    tags:
      - name: 'doctrine.orm.entity_listener'
        event: 'postUpdate'
        entity: '%sylius.model.product_taxon.class%'
      - name: 'doctrine.orm.entity_listener'
        event: 'postPersist'
        entity: '%sylius.model.product_taxon.class%'
      - name: 'doctrine.orm.entity_listener'
        event: 'postRemove'
        entity: '%sylius.model.product_taxon.class%'

  setono_sylius_elasticsearch_plugin.provider.indexable:
    class: 'Setono\SyliusElasticsearchPlugin\Provider\Indexable'
    decorates: 'fos_elastica.indexable'
    arguments:
      - []
