name: "build"
on:
    push:
        branches:
            - "*.x"
        paths-ignore:
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "**/*.md"
    workflow_dispatch: ~

env:
    APP_ENV: "test"
    PHP_EXTENSIONS: "intl, mbstring"

jobs:
    coding-standards:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.1" # Always use the lowest version of PHP since a higher version could create actual syntax errors in lower versions

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    coverage: "none"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v2"

            -   name: "Validate composer"
                run: "composer validate --strict"

            -   name: "Check composer normalized"
                run: "composer normalize --dry-run"

            -   name: "Check style"
                run: "composer check-style"

            -   name: "Rector"
                run: "vendor/bin/rector process --dry-run"

    dependency-analysis:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.1"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "composer-require-checker, composer-unused, flex"

            -   name: "Remove require-dev section in composer.json"
                run: "composer config --unset require-dev"
            
            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v2"

            -   name: "Run maglnet/composer-require-checker"
                run: "composer-require-checker check --config-file=$(pwd)/composer-require-checker.json --ignore-parse-errors"

            -   name: "Run composer-unused/composer-unused"
                run: "composer-unused"

    static-code-analysis:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.1"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Remove sylius/sylius from composer.json"
                run: "composer remove --dev --no-update --no-plugins --no-scripts sylius/sylius"
            
            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v2"

            -   name: "Static analysis"
                run: "vendor/bin/psalm --php-version=${{ matrix.php-version }}"
